{% set name = "FreeClimber" %}
{% set version = "0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: "https://github.com/adamspierer/FreeClimber.git"
  git_tag: dev

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - argparse >=1.1
    - ffmpeg >=0.2.0
    - matplotlib >=3.1.3
    - numpy >=1.18.1
    - pandas >=1.0.0
    - pip >=20.0.2
    - python 3.7.6
    - scipy >=1.4.1
    - time
    - trackpy >=0.4.2
    - wxPython >=4.0.4
    
  run:
    - argparse >=1.1
    - ffmpeg >=0.2.0
    - matplotlib >=3.1.3
    - numpy >=1.18.1
    - pandas >=1.0.0
    - python 3.7.6
    - scipy >=1.4.1
    - time
    - trackpy >=0.4.2
    - wxPython >=4.0.4

        
test:
  imports:
    
about:
  home: "https://github.com/adamspierer/FreeClimber.git"
  license: "UNKNOWN"
  license_family: "OTHER"
  license_file: ""
  summary: "Background subtracting particle detector that quantifies vertical velocity of particles using a local linear regression"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - "adamspierer"
